### ISSUE TITLE
Optimization: Let integrators go to sleep if all of their controllers are asleep

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModStewards/Waterfall#119]
![image](https://user-images.githubusercontent.com/9804078/182859124-d9341448-753f-4cbc-a552-df251a016372.png)
The StockWaterfallEffects poodle is incredibly expensive, but a lot of its effect modifiers are just piping atmospheredepth into a shader param.  Once you're in space this value is never going to change and we should stop updating it.

**Comment by JonnyOThan** [comment]
Er I don't think this one is actually done.  The optimizations I've added so far will stop updating the controllers on a module if ALL of them go to sleep - but if you have an engine running in space the atmosphereDepth will still be evaluated all the time.

I think.  It's been a while since I wrote that stuff.

**Comment by JonnyOThan** [comment]
I think this basically boils down to having integrators stop updating when all of their inputs are asleep.  We already know when controllers are asleep (though it's not actually stored on the controller).  Then when all of the controllers used by an integrator are asleep, the integrator can go to sleep and stop updating.

When a controller wakes up again, we'd need to go wake up all the integrators that depend on it.

**Comment by JonnyOThan** [comment]
This should be fixed in #164

**Comment by JonnyOThan** [comment]
Er I guess it just needs the next release label

**Comment by ChrisAdderley** [comment]
Released in 0.10.0
