### ISSUE TITLE
Optimization: remove effect modifiers that use missing controllers

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModStewards/Waterfall#120]
A lot of effects in Stock Waterfall Effects are missing controllers (e.g. mach controller for vernierRcsFx); we could remove these modifiers from the lists so they don't cost anything.  This isn't super straightforward though because they still need to show up in the right place in the editor in case the controller gets created.

**Comment by ChrisAdderley** [comment]
Released in 0.10.0
