### ISSUE TITLE
Potential memory leaks identified by KSPCommunityFixes

### ISSUE THREAD

**Issue by Gordon-Dry** [KSPModStewards/Waterfall#121]
Latest version of KSPCommunityFixes reports on some potential memory leaks on scene changes. A quick look in the log after scene change to Flight Scene shows 1 potential location in Waterfall where a leak might exist:
`[LOG 21:17:03.643] [KSPCF:MemoryLeaks] A destroyed Waterfall:WaterfallUI instance is owning a onGUIApplicationLauncherDestroyed GameEvents callback. No action has been taken, but unless this mod is relying on this pattern, this is likely a memory leak.`

**Comment by ChrisAdderley** [comment]
Released in 0.10.0
