### ISSUE TITLE
Editing Throttle Controller on MultiModeEngine causes loss of engine ID

### ISSUE THREAD

**Issue by SabrCat** [KSPModStewards/Waterfall#125]
When editing a throttle controller on e.g. a Panther engine, to change e.g. the spool up time, pressing "apply" makes the internal WaterfallFX module loose the engine ID of "Wet", and it instead becomes nothing. This loss of engine Module also applies when the Module is exported to clipboard, one has to manually re-enter the engine ID. 
This issue makes tuning the throttle response speed properly quite a pain as I have to restart my game with changed configs every time I want to make a change.

**Comment by ChrisAdderley** [comment]
Released in 0.10.0
