### ISSUE TITLE
Ignition and Flameout Engine Event Controllers trigger incorrectly in MultiModeEngines

### ISSUE THREAD

**Issue by SabrCat** [KSPModStewards/Waterfall#126]
Adding an Ignition and a Flameout event controller to a multi mode engine like e.g. a panther leads to some bad behavior. 
In dry mode it works correctly, ignition and flameout trigger with engine on or off. 
However, flameout also triggers when the engine switches from dry to wet mode, and ignition triggers when switching back to dry mode. It is also not possible to give the controller an engine ID to listen to, so it wrongly responds to dry mode even for FX that target the wet mode.
A better implementation of this might be to add a engineID parameter to the event controller. Additionally it would be helpful to have a mode switch or rather a mode enable and a mode disable module. Only the first change of being able to target a specific engineID with the event controller would already allow FX like e.g. afterburner ignition or flameout, which is currently not possible.

**Comment by ChrisAdderley** [comment]
Released in 0.10.0
