### ISSUE TITLE
Engine lights have incorrect layer setup

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModStewards/Waterfall#130]
I haven't tested this, but I'm pretty sure this is why you sometimes see bright lights inside IVA after takeoff when waterfall is installed.  Since the internal space and external spaces are in different coordinate systems, and the lights are in both layers, then they show up in the internal space but at weird positions (using their external coordinates, not where the engines appear to be).

![image](https://github.com/post-kerbin-mining-corporation/Waterfall/assets/9804078/0b97da52-aa2d-402b-9142-6365b4983ccb)

If we wanted to support engine lights in IVA, there would need to be new code to make a copy of the light at the correct coordinates and layer, then keep it in sync with the external one.  Not terribly hard, but just fixing the layers on the light model will at least fix the bug.

**Comment by JonnyOThan** [comment]
did you fix this one? cause I didn't...  it needs to be updated in the .mu file.  I don't see any updates in the dev branch

**Comment by ChrisAdderley** [comment]
It's fixed locally in the particles branch. Once that gets moved to dev it'll be sorted

**Comment by ChrisAdderley** [comment]
Released in 0.10.0
