### ISSUE TITLE
perlin noise random controller doesn't work

### ISSUE THREAD

**Issue by KnightofStJohn** [KSPModStewards/Waterfall#48]
I've noticed that perlin noise doesn't do anything anymore. I noticed it since 0.5.0. I think it worked before but not sure.

the issue is that if i create a new controller, set it to perlin, and let it control some mesh variable, like for instance the linear expansion of a cylinder, it still just outputs a standard random variable, not perlin. Even when I check the "override" button and manually slide the controller, it doesn't actually do anything, and the mesh keeps acting as if it's getting input from a standard random variable.

The same happens if I manually add a controller in the .cfg file. it also still gives a standard random variable output.

Technically I don't know if it gives a standard random variable, it just looks really fast, so it could still be a high frequency perlin, but what I am sure is that I cant override it.

Also: when I open up the "edit" gui to change the controller settings, it has "random" selected, and not "perlin" even though it's set up as a perlin.

**Comment by KnightofStJohn** [comment]
this was a misunderstanding on my part.
the only bug pertaining to this is that the override doesn't work for random controllers in general.

**Comment by ChrisAdderley** [comment]
override works fine in latest dev for me.
