### ISSUE TITLE
using ADD, MULTIPLY or SUBTRACT on a variable that isn't defined by a modifier makes the variable change continuously

### ISSUE THREAD

**Issue by KnightofStJohn** [KSPModStewards/Waterfall#52]
This is a bug that is very similar to a previously fixed bug.
If you do not first set a variable, like scale, position, material float,... using a modifier on REPLACE  (controlled by a controller), then using an ADD, MULTIPLY or SUBTRACT modifier on the variable makes it change continuously according to the modifier type.

Example:
have a cylinder with ExpandOffset = 1 by just setting the value on 1 using the material editor UI.
then add a ADD modifier that adds a value between 1 and 2 to the ExpandOffset based on, for instance, throttle.
the modifier will keep adding that value every tick, and the cylinder will start expanding indefinitely.

I think the intended behavior is that it should add once, even if the original variable isn't set by a REPLACE modifier first.

**Comment by ChrisAdderley** [comment]
Resolved in latest dev.
