### ISSUE TITLE
Plume always visible on engines with minimal throttle

### ISSUE THREAD

**Issue by Vladimir-csp** [KSPModStewards/Waterfall#57]
Hi!
I'm using a patch that sets minimal throttle on most engines. It seems to cause waterfall plumes to be always visible, unless flamed out on empty fuel.

**Comment by ChrisAdderley** [comment]
What does 'minimal throttle' mean? How is this achieved? Are there reproduction steps?

**Comment by Vladimir-csp** [comment]
Sorry, I meant `minThrust` parameter, for simulating limited throttle depth.
Set `minThrust = 12` for Terrier for example. If it has fuel available, it will show plume even if disabled.

**Comment by ChrisAdderley** [comment]
You can get the dev branch dll and see if this solves the issue for you.

**Comment by Vladimir-csp** [comment]
Unfortunately, no change.
![image](https://user-images.githubusercontent.com/4061903/110739837-0009e400-8243-11eb-87a4-bd34ce607f0d.png)

**Comment by ChrisAdderley** [comment]
Ok, I think fixed now. Squad code is weird, no surprise there. Will be in next release (and dev now).

**Comment by Vladimir-csp** [comment]
It's fixed, thanks!

**Comment by ChrisAdderley** [comment]
Released with 0.6.1
